//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTicketbookingModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public Nullable<int> Mid { get; set; }
        public int Cid { get; set; }
        public int Bid { get; set; }
        public Nullable<int> SeatNo { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Movie Movie { get; set; }
    }
}
